### ISSUE TITLE
New Game: Surat Al-Asr

### ISSUE THREAD

**Issue by ashes999** [deengames/a-day-and-a-night#100]
- Play the surah (audio). You have to pre-load it.
- Show the Arabic text, and English, nicely scrolling. (Arabic can scroll, and English can be closed-captioning style)
- For art, we need to decide on our overall design, and add the art borders/etc. as applicable
- You can skip it; doing so _fades out_, not abruptly stops, audio.

Reference video: https://www.youtube.com/watch?v=-ocpbPfsQ9g

Add some actual event/dialog from Saif (the main character):

> These words ... Recited to me only a day ago, changed my life forever.
> I must seek redemption for the acts that I have done.
> I must flee. If the King's men find me, I am finished.
> (map changes)
> This small village should be a good place to hide for now.

Todo:
- [ ] Intro cutscene (story/dialog)
- [ ] Fix bug: transition
- [ ] Fix bug: time shouldn't start yet.
