### ISSUE TITLE
Apothecary's Map/Hut

### ISSUE THREAD

**Issue by ashes999** [deengames/a-day-and-a-night#133]
Functionality (Code):
- [X] Cackling apothecary (poison maker)
- [ ] Dragon's Grass (herb) grows near pond
- [ ] Apothecary makes dragon-heal herb with dragon grass
- [ ] Dragon-heal heals adult dragon

Map:
- [x] Make it look appropriately gloomy/scary

Art:
- [x] Apothecary NPC
- [x] Make it look appropriately gloomy/scary.

Level: make this SCARY somehow. Maybe you have glowing red eyes randomly in the background, or scary background noises / screams, or something.
