### ISSUE TITLE
Masjid Map

### ISSUE THREAD

**Issue by ashes999** [deengames/a-day-and-a-night#134]
- [x] King's statue (shirk => negative points)
- [x] Positive points for not worshipping it
- [x] Eventually, shaykh gives tafseer of Surat Al-Asr (major points, hint backstory)
- [x] Can smash statue if have sword (R)
- [x] Guy who gets shocked if you pray 3x to the statue (K)
- [x] Student who hints/counts times talked to him; interrupted if 5x (K)
