### ISSUE TITLE
Inn Map

### ISSUE THREAD

**Issue by ashes999** [deengames/a-day-and-a-night#135]
- [x] Inn (outside)
- [x] Inn (two floors)
- [x] Your room (start; sword under bed)
- [x] Inventory or something (gotta store sword, armour, dragon egg, ...)
- [x] First Event (pay or walk out -- good or bad deed)
