### ISSUE TITLE
Dragon Epic (Main map)

### ISSUE THREAD

**Issue by ashes999** [deengames/a-day-and-a-night#136]
Maps:
- [x] Egg area outside (wilderness)
- [x] Barn (with egg placeholder location)
- [x] Fish pond
- [x] Add chick to barn

Events:
- [x] Barn building
- [x] I can catch fish
- [x] Can catch armour

Art:
- [x] Fish for fish pond
- [x] Roll of hay
- [x] Pitchfork
- [x] Hay/straw (on the floor) -- why can't we copy over the autotile?
- [x] Add the new art into the map
- [ ] Fishing rod (inventory image)
- [ ] Fishing rod (icon) (24x24)
- [ ] Matching fish icon for item in inventory (24x24)

Other:
- [x] Add gurgling audio to pond
- [ ] Add icons to facesets for items
