### ISSUE TITLE
Robber Epic (main map)

### ISSUE THREAD

**Issue by ashes999** [deengames/a-day-and-a-night#137]
- [ ] House with robbers outside
- [ ] Talk to them. Talk enough times to dissuade them. 
- [ ] At time `X`: they raid. Timer 2 starts.
- [ ] During raid: "AIEE!" kill the robberz.
- [ ] After time `X+Y`, they flee.
