### ISSUE TITLE
Training House Map

### ISSUE THREAD

**Issue by ashes999** [deengames/a-day-and-a-night#138]
Planning:
- ~~Create a pen-and-paper diagram of how the dojo will be: path up the mountain, exterior, and interior.~~
- [x] Create the exterior map at the end of the path (same map)
- [x] Create the interior map
- [x] How do you get to B1?

Actual map events:
- [x] Path leading up to the dojo (one of two forks)
- [x] Path boulders: if they hit you, you're incapacitated for 1 minute of game time
- [x] Train with them (up to 5x)
- [x] Challenge/defeat leader. He broke his leg :(

Art:
- [x] At least some sort of signs that it's a dojo (training dummy, mats, etc.)
- [x] Leader sprite (make it epic)
- [x] Leader face
- [ ] Optional: one frame of him with a broken leg (not bandaged)
- [x]  Beat-up face
- [x] Guard dog (including face)

Generator: http://www.famitsu.com/freegame/tool/chibi/index1.html

**Tasks for @al3izz:**
- [x] Download and install the trial version of RPG Maker VX Ace
- [x] Clone the ADAAN repository
