### ISSUE TITLE
Blacksmith's Forge Map

### ISSUE THREAD

**Issue by ashes999** [deengames/a-day-and-a-night#139]
- [x] Blacksmith ("if I had / you help me find ore, I could make ...")
- [x] Give him iron (twice)
- [x] Give him iron (third one): gives you equipment (shield), and says hmm, Chet might want to talk to you (NB: you don't auto-wear the shield if you're already wearing the dragon one)
- [x] Give him dragon scale (shield) 
- [x] Numerous small actions to mess him up: fan bellows a few times, poke the fire with your sword, knock over water barrel. He can't forge now (see above)
- [x] Give him five pieces of iron ("eh, special order from Chet? ...ok ..."); he's tired and won't make more stuff now.

Artwork by @silatsaif (find it or make it)
- [x] Blacksmith anvil
- [x] Forge (firey place)
- [ ] Iron ore (inventory-size image, recolour the gold ore icon in VX Ace) - @BLACK8EARD 
- [ ] Dragon scale (icon-size image) - @BLACK8EARD 
- [x] Bellows (thing you blow to fan the flames) - @silatsaif 
- [x] Water barrel - @silatsaif 

Points:
- [x] Iron shield (rebellion/good; hint that he keeps one)
- [x] Dragon shield (rebellion/bad)
- [x] Tired (kingdom/good)
- [x] Mess up forge (kingdom/bad)
