### ISSUE TITLE
Cave + Chet's Area

### ISSUE THREAD

**Issue by ashes999** [deengames/a-day-and-a-night#140]
Small outdoor areas.
- [x] The second fork from #138 leads to a cave in the mountain
- [x] Go through cave and into a meadow/cliff clearing map with a house
- [x] Ore regenerates in the cave
- [x] Chet (rebel leader); hints at redemption tonight
- [x] Spare the king's life? Yes => hmm, no => He's a killer and deserves worse

Audio:
- [x] Bats in cave
- [x] Dripping noise in cave
- [x] Lake in cave?

Art:
- [x] Pick-axe inventory image from @silatsaif
