### ISSUE TITLE
Fighting Mini-Game

### ISSUE THREAD

**Issue by ashes999** [deengames/a-day-and-a-night#179]
Instead of punching him out, there should actually be a mini-game to fight the dojo dudes. Because the discussion is actually boring.

It's a rock-paper-scissors type battle.
- [x] Basic RPS battle where you win/lose
- [x] Up to three lives; ties just prolong the fight
- [x] N HP, and P HP lost per battle
- [x] Reward for being faster than the NPC
