### ISSUE TITLE
Primary Quests Chain

### ISSUE THREAD

**Issue by ashes999** [deengames/a-day-and-a-night#210]
After #208 
- [ ] 100 people: #217 
- [x] Inn stuff => told to go to Blacksmith
- [x] Two shields => told to talk to Boss
- [x] Strong? Train martial arts => told to defeat robbers
- [x] Robbers => told to go to Boss
- [x] Busy, told to go to apothecary
- [x] Told to get mushrooms at night time (forest)
- [ ] See and save dragon; you run to apothecary after
- [ ] Find dragon scale (optional)
- [ ] Apothecary makes dragon-heal salve
- [ ] You heal the dragon and its your friend
- [ ] Boss confrontation (#209)
