### ISSUE TITLE
Main Map

### ISSUE THREAD

**Issue by ashes999** [deengames/a-day-and-a-night#81]
- [x] Guards at the front gate; message "they'll see me if I leave"
- [x] Starting cash ($100)
- [x] Begger (soldier but too poor to arm himself)
- [x] Give coins (75 => he armours up)
